name: webview_pwa
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  js: ^0.6.7
  modal_bottom_sheet: ^3.0.0
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
